#
# Makefile
#
# Makefile for Poco WebTunnel library
#

include $(POCO_BASE)/build/rules/global

objects = LocalPortForwarder RemotePortForwarder PortReflector \
	TunnelSocket TunnelSocketImpl \
	SocketDispatcher Protocol

target         = PocoWebTunnel
target_version = 1
target_libs    = PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/lib
