#
# Makefile
#
# $Id: //poco/1.4/WebTunnel/samples/Makefile#3 $
#
# Makefile for Poco WebTunnel Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C WebTunnelClient $(MAKECMDGOALS)
	$(MAKE) -C WebTunnelAgent $(MAKECMDGOALS)
