#
# Makefile
#
# $Id: //poco/1.6/OSP/WebEvent/Makefile#1 $
#
# Makefile for Poco OSP WebEvent
#

.PHONY: bundle
clean all: bundle
bundle:
	$(MAKE) -f Makefile-Library $(MAKECMDGOALS)
	$(MAKE) -f Makefile-Bundle $(MAKECMDGOALS)
