#
# Makefile
#
# $Id: //poco/1.7/RemotingNG/testsuite/Makefile#2 $
#
# Makefile for Poco Remoting testsuite
#

include $(POCO_BASE)/build/rules/global

objects = \
	Driver \
	RemotingTest \
	EventFilterTest \
	RemotingTestSuite \
	Tester \
	ITester \
	TesterEventSubscriber \
	TesterClientHelper \
	TesterEventDispatcher \
	TesterProxy \
	TesterProxyFactory \
	TesterRemoteObject \
	TesterServerHelper \
	TesterSkeleton \
	TesterStub

target         = testrunner
target_version = 1
target_libs    = PocoRemotingNG PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
