#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Dataflow samples
#

.PHONY: clean all

clean all:
	$(MAKE) -C ClockDataflow $(MAKECMDGOALS)
	$(MAKE) -C SimpleDataflow $(MAKECMDGOALS)
	$(MAKE) -C XMLDataflow $(MAKECMDGOALS)
