#
# Makefile
#
# $Id$
#
# Makefile for IoT GNSS NMEA Library
#

include $(POCO_BASE)/build/rules/global

objects = Sentence SentenceDecoder RMCProcessor GGAProcessor

target         = IoTGNSSNMEA
target_version = 1
target_libs    = PocoGeo PocoFoundation

include $(POCO_BASE)/build/rules/lib
