ifdef COMPONENTS_FILE
include $(COMPONENTS_FILE)
else


###
### Platform Components
###

export MACCHINA_ENABLE_JS=1
export MACCHINA_ENABLE_JWT=1
export MACCHINA_ENABLE_DATA=1
export MACCHINA_ENABLE_DATA_SQLITE=1
#export MACCHINA_ENABLE_DATA_MYSQL=1
#export MACCHINA_ENABLE_DATA_ODBC=1
#export MACCHINA_ENABLE_DATA_POSTGRESQL=1
export MACCHINA_ENABLE_ACTIVERECORD=1
export MACCHINA_ENABLE_OSP_WEB=1
export MACCHINA_ENABLE_OSP_WEBEVENT=1
export MACCHINA_ENABLE_REMOTINGNG_TCP=1
export MACCHINA_ENABLE_REDIS=1
export MACCHINA_ENABLE_MONGODB=1
export MACCHINA_ENABLE_XSD=1


###
### Protocols
###

export MACCHINA_ENABLE_PROTOCOLS=1
export MACCHINA_ENABLE_MQTT=1
export MACCHINA_ENABLE_XBEE=1
export MACCHINA_ENABLE_BTLE=1
export MACCHINA_ENABLE_UDP=1
export MACCHINA_ENABLE_MODBUS=1
export MACCHINA_ENABLE_MODBUS_RTU=1
export MACCHINA_ENABLE_MODBUS_TCP=1
export MACCHINA_ENABLE_MODBUS_DEVICE=1
export MACCHINA_ENABLE_CAN=1
export MACCHINA_ENABLE_WEBTUNNEL=1


###
### Services
###

export MACCHINA_ENABLE_SERVICES=1
export MACCHINA_ENABLE_WEBEVENT=1
export MACCHINA_ENABLE_SETTINGS=1
export MACCHINA_ENABLE_DEVICESTATUS=1
export MACCHINA_ENABLE_NETWORKENVIRONMENT=1
export MACCHINA_ENABLE_UNITSOFMEASURE=1
export MACCHINA_ENABLE_MOBILECONNECTION=1
export MACCHINA_ENABLE_MOBILECONNECTION_LEGATO=1


###
### Devices
###

export MACCHINA_ENABLE_DEVICES=1
export MACCHINA_ENABLE_DATAPOINTS=1
export MACCHINA_ENABLE_SERIAL=1
export MACCHINA_ENABLE_LINUXDEVICES=1
export MACCHINA_ENABLE_TF=1
export MACCHINA_ENABLE_SIMULATION=1
export MACCHINA_ENABLE_XBEESENSOR=1
export MACCHINA_ENABLE_XDK=1
export MACCHINA_ENABLE_CISS=1
export MACCHINA_ENABLE_SENSORTAG=1
export MACCHINA_ENABLE_GNSS=1


###
### WebUI
###

export MACCHINA_ENABLE_WEBUI=1
export MACCHINA_ENABLE_WEBUI_CONSOLE=1
export MACCHINA_ENABLE_WEBUI_SETTINGS=1
export MACCHINA_ENABLE_WEBUI_BUNDLEADMIN=1
export MACCHINA_ENABLE_WEBUI_PLAYGROUND=1
export MACCHINA_ENABLE_WEBUI_SERVICES=1
export MACCHINA_ENABLE_WEBUI_SYSTEMINFORMATION=1
export MACCHINA_ENABLE_WEBUI_DEVICES=1
export MACCHINA_ENABLE_WEBUI_DEVICETREE=1
export MACCHINA_ENABLE_WEBUI_GPIO=1
export MACCHINA_ENABLE_WEBUI_GNSS=1
export MACCHINA_ENABLE_WEBUI_MQTT=1
export MACCHINA_ENABLE_WEBUI_PERIPHERALBROWSER=1
export MACCHINA_ENABLE_WEBUI_LOGFILES=1


###
### Samples
###

export MACCHINA_ENABLE_SAMPLES=1


endif # COMPONENTS_FILE


###
### Do not disable or modify the following
###

export MACCHINA_HAVE_COMPONENTS=1
