#
# Makefile
#
# Makefile for Poco Redis
#

include $(POCO_BASE)/build/rules/global

objects = AsyncReader Array Client Command Error Exception RedisStream RedisEventArgs Type

target         = PocoRedis
target_version = $(LIBVERSION)
target_libs    = PocoFoundation PocoNet

include $(POCO_BASE)/build/rules/lib
