#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Dataflow XML Parser 
#

include $(POCO_BASE)/build/rules/global

INCLUDE += -I../Engine/include

objects = Parser

target         = IoTDataflowXML
target_version = 1
target_libs    = IoTDataflowEngine PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/lib
