#
# Makefile
#
# Makefile for Code Cache Utility
#

include $(POCO_BASE)/build/rules/global

objects = CCUtility

target         = ccutil
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
