#
# Makefile
#
# $Id: //poco/1.7/OSP/NetEnv/Makefile#1 $
#
# Makefile for OSP NetEnv
#

.PHONY: bundle
clean all: bundle
bundle:
	$(MAKE) -f Makefile-Library $(MAKECMDGOALS)
	$(MAKE) -f Makefile-Bundle $(MAKECMDGOALS)
