#
# Makefile
#
# $Id: //poco/1.7/OSP/samples/BundleServer/Makefile#1 $
#
# Makefile for Poco BundleServer
#

include $(POCO_BASE)/build/rules/global

objects = BundleServer

target         = BundleServer
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
