#
# Makefile
#
# $Id: //poco/1.7/OSP/samples/BundleContainer/Makefile#1 $
#
# Makefile for Poco BundleContainer
#

include $(POCO_BASE)/build/rules/global

objects = BundleContainer

target         = BundleContainer
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
