#
# Makefile
#
# Makefile for Poco BundleContainer
#

include $(POCO_BASE)/build/rules/global

objects = BundleContainer

target         = BundleContainer
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
