#
# Makefile
#
# $Id: //poco/1.4/OSP/Web/Makefile#1 $
#
# Makefile for Poco OSPWeb 
#

.PHONY: bundle
clean all: bundle
bundle:
	$(MAKE) -f Makefile-Library $(MAKECMDGOALS)
	$(MAKE) -f Makefile-Bundle $(MAKECMDGOALS)
