//
// RemoteObject.h
//
// $Id: //poco/1.7/RemotingNG/include/Poco/RemotingNG/RemoteObject.h#1 $
//
// Library: RemotingNG
// Package: ORB
// Module:  RemoteObject
//
// Definition of the RemoteObject class.
//
// Copyright (c) 2006-2014, Applied Informatics Software Engineering GmbH.
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//


#ifndef RemotingNG_RemoteObject_INCLUDED
#define RemotingNG_RemoteObject_INCLUDED


#include "Poco/RemotingNG/Identifiable.h"
#include "Poco/Mutex.h"


namespace Poco {
namespace RemotingNG {
	
	
class RemotingNG_API RemoteObject: public Identifiable
	/// RemoteObject is the base class for all RemoteObject
	/// classes generated by the RemotingNG code generator,
	/// as well as for Proxy.
	///
	/// For every service object, the RemotingNG code generator
	/// generates a RemoteObject that is a subclass of the
	/// service object's interface class.
{
public:
	typedef Poco::AutoPtr<RemoteObject> Ptr;

	RemoteObject(const Poco::RemotingNG::Identifiable::ObjectId& oid);
		/// Creates a RemoteObject with the given ID.

	virtual ~RemoteObject();
		/// Destroys the RemoteObject.

	virtual void remoting__enableRemoteEvents(const std::string& protocol);
		/// Enables remote events for this RemoteObject instance, using the
		/// given protocol.
		///
		/// Events will be delivered using the Transport for the given protocol.
		/// Can be called multiple times for the same URI with different protocols.
		///
		/// Must be overridden by subclasses if the service object has events.
		/// The default implementation does nothing.

protected:
	RemoteObject();
		/// Creates a RemoteObject.

	Poco::FastMutex& remoting__mutex() const;
		/// Returns a reference to the object's mutex.
	
private:
	mutable Poco::FastMutex _mutex;
};


//
// inlines
//
inline Poco::FastMutex& RemoteObject::remoting__mutex() const
{
	return _mutex;
}


} } // namespace Poco::RemotingNG


#endif // RemotingNG_RemoteObject_INCLUDED
