#
# Makefile
#
# $Id$
#
# Makefile for Poco OPC Server
#

include $(POCO_BASE)/build/rules/global

objects = OPCServer

target         = OPCServer
target_version = 1
target_libs    = PocoOPC PocoFoundation

include $(POCO_BASE)/build/rules/exec
