#
# Makefile
#
# $Id$
#
# Makefile for macchina.io SimpleDataflow sample 
#

include $(POCO_BASE)/build/rules/global

INCLUDE += -I$(PROJECT_BASE)/dataflow/Engine/include

objects = SimpleDataflow

target         = SimpleDataflow
target_version = 1
target_libs    = IoTDataflowEngine PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
