#
# Makefile
#
# $Id$
#
# Makefile for macchina.io launcher
#

include $(POCO_BASE)/build/rules/global

objects = MacchinaLauncher

target         = macchina-launcher
target_version = 1
target_libs    = PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
