#
# Makefile
#
# Makefile for Poco WebTunnel client C library
#

include $(POCO_BASE)/build/rules/global

objects = webtunnelclient

target         = WebTunnelClient
target_version = 1
target_libs    = PocoWebTunnel PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/lib
