#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Dataflow Engine 
#

include $(POCO_BASE)/build/rules/global

objects = AttributedObject Port Inlet Outlet Node TimingNodes Scheduler Dataflow \
	NodeFactory CoreNodeFactory

target         = IoTDataflowEngine
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
