#
# Makefile
#
# Makefile for Poco Geo library
#

include $(POCO_BASE)/build/rules/global

objects = Angle LatLon

target         = PocoGeo
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
