#
# Makefile
#
# $Id$
#
# Makefile for Poco OPC Client
#

include $(POCO_BASE)/build/rules/global

objects = OPCClient

target         = OPCClient
target_version = 1
target_libs    = PocoOPC PocoFoundation

include $(POCO_BASE)/build/rules/exec
