#
# Makefile
#
# $Id$
#
# Makefile for Poco OPC Server
#

include $(POCO_BASE)/build/rules/global

INCLUDE += -I$(PROJECT_BASE)/protocols/OPC/include

objects = OPCServer

target         = OPCServer
target_version = 1
target_libs    = IoTOPC PocoFoundation

include $(POCO_BASE)/build/rules/exec
