#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Services
#

.PHONY: clean all

clean all:
	$(MAKE) -C WebEvent $(MAKECMDGOALS)
	$(MAKE) -C DeviceStatus $(MAKECMDGOALS)
	$(MAKE) -C NetworkEnvironment $(MAKECMDGOALS)
	$(MAKE) -C MobileConnection $(MAKECMDGOALS)
