#
# Makefile
#
# $Id$
#
# Makefile for macchina.io server 
#

include $(POCO_BASE)/build/rules/global

objects = MacchinaServer

target         = macchina
target_version = 1
target_libs    = PocoOSP PocoZip PocoNet PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
