#
# Makefile
#
# Makefile for Poco RemotingNG Samples
#

.DEFAULT all:
	$(MAKE) -C Pizzeria $(MAKECMDGOALS)
	$(MAKE) -C PizzeriaClient $(MAKECMDGOALS)
	$(MAKE) -C TimeServerTCP $(MAKECMDGOALS)
	$(MAKE) -C TimeClientTCP $(MAKECMDGOALS)
