#
# Makefile
#
# Makefile for Poco OSPWeb testsuite
#

include $(POCO_BASE)/build/rules/global

objects = WebTestSuite Driver \
	MediaTypeMapperTest WebServerDispatcherTest

target         = testrunner
target_version = 1
target_libs    = PocoOSPWeb PocoOSP PocoZip PocoNet PocoUtil PocoXML PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
