#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Devices
#

.PHONY: clean all

clean all:
	$(MAKE) -C Devices $(MAKECMDGOALS)
	$(MAKE) -C Serial $(MAKECMDGOALS)
	$(MAKE) -C Tf $(MAKECMDGOALS)
	$(MAKE) -C Simulation $(MAKECMDGOALS)
