#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Devices
#

.PHONY: clean all

clean all:
	$(MAKE) -C Devices $(MAKECMDGOALS)
	$(MAKE) -C Serial $(MAKECMDGOALS)
	$(MAKE) -C Tf $(MAKECMDGOALS)
	$(MAKE) -C Simulation $(MAKECMDGOALS)
	$(MAKE) -C Linux $(MAKECMDGOALS)
	$(MAKE) -C XBeeSensor $(MAKECMDGOALS)
	$(MAKE) -C XDK $(MAKECMDGOALS)
	$(MAKE) -C SensorTag $(MAKECMDGOALS)
	$(MAKE) -C GNSS/NMEA $(MAKECMDGOALS)
	$(MAKE) -C GNSS $(MAKECMDGOALS)
