#
# Makefile
#
# $Id: //poco/1.4/Geo/testsuite/Makefile#1 $
#
# Makefile for Poco Geo testsuite
#

include $(POCO_BASE)/build/rules/global

objects = GeoTestSuite Driver \
	AngleTest LatLonTest

target         = testrunner
target_version = 1
target_libs    = PocoGeo PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
