#
# Makefile
#
# Makefile for Poco OSP Unit Library
#

include $(POCO_BASE)/build/rules/global

objects = LogTestResult TestCase TestFactory

target         = PocoOSPUnit
target_version = 2
target_libs    = CppUnit PocoFoundation

include $(POCO_BASE)/build/rules/lib
