#
# Makefile
#
# $Id$
#
# Makefile for Poco OPC testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver OPCTest OPCTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoOPC PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec

