#
# Makefile
#
# $Id: //poco/1.4/protocols/OPC/samples/runjs/Makefile#1 $
#
# Makefile for jsrun
#

include $(POCO_BASE)/build/rules/global

INCLUDE += -I$(PROJECT_BASE)/protocols/OPC/include

objects = jsrun

target         = jsrun
target_version = 1
target_libs    = v8 IoTOPC PocoJSCore PocoNetSSL PocoRemotingNG PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
