#
# Makefile
#
# $Id: //poco/1.4/JS/Core/Makefile#7 $
#
# Makefile for Poco JS Core library
#

include $(POCO_BASE)/build/rules/global

objects = Wrapper PooledIsolate \
	LoggerWrapper ConsoleWrapper SystemWrapper DateTimeWrapper LocalDateTimeWrapper \
	ConfigurationWrapper ApplicationWrapper URIWrapper TimerWrapper \
	JSExecutor

target         = PocoJSCore
target_version = 1
target_libs    = PocoUtil PocoXML PocoFoundation v8

include $(POCO_BASE)/build/rules/lib
