#
# Makefile
#
# Makefile for OSP StripBundle Utility
#

include $(POCO_BASE)/build/rules/global

objects = StripBundle

target         = stripbundle
target_version = 1
target_libs    = PocoZip PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
