#
# Makefile
#
# Makefile for OSP StripBundle Utility
#

include $(POCO_BASE)/build/rules/global

objects = StripBundle

target         = strip-bundle
target_version = 1
target_libs    = PocoZip PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
