#
# Makefile
#
# $Id$
#
# Makefile for Poco OPC library
#

include $(POCO_BASE)/build/rules/global

objects = open62541 Client Server Types

target         = PocoOPC
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
