#
# Makefile
#
# $Id: //poco/1.7/OSP/BundleCreator/Makefile#1 $
#
# Makefile for Poco BundleContainer
#

include $(POCO_BASE)/build/rules/global

objects = BundleCreator ManifestInfo

target         = bundle
target_version = 1
target_libs    = PocoFoundation PocoXML PocoUtil PocoOSP PocoZip $(POCO_LICENSING)

include $(POCO_BASE)/build/rules/exec
