#
# Makefile
#
# Makefile for Poco BundleContainer
#

include $(POCO_BASE)/build/rules/global

objects = BundleCreator ManifestInfo

target         = bundle
target_version = 1
target_libs    = $(POCO_LICENSING) PocoOSP PocoZip PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
