#
# Makefile
#
# Makefile for ROS protocol
#

include $(POCO_BASE)/build/rules/global

objects = BridgeClientApp

target         = rosclient
target_version = 1
target_includes = $(PROJECT_BASE)/protocols/ROS/include
target_libs    = IoTROS PocoNet PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
