#
# Makefile
#
# Makefile for macchina.io Bt LE Library Skeleton
#

include $(POCO_BASE)/build/rules/global

objects = \
	IPeripheral \
	IPeripheralBrowser \
	IPeripheralManager \
	PeripheralBrowserEventDispatcher \
	PeripheralBrowserRemoteObject \
	PeripheralBrowserServerHelper \
	PeripheralBrowserSkeleton \
	PeripheralManagerRemoteObject \
	PeripheralManagerServerHelper \
	PeripheralManagerSkeleton \
	PeripheralEventDispatcher \
	PeripheralRemoteObject \
	PeripheralServerHelper \
	PeripheralSkeleton

target          = IoTBtLESkel
target_version  = 1
target_includes = ../include
target_libs     = IoTBtLE PocoRemotingNG PocoOSP PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/lib
