hunter_config(PocoCpp VERSION 1.9.1
  #GIT_SUBMODULE thirdparty/poco
  CMAKE_ARGS
  BUILD_SHARED_LIBS=ON
  POCO_STATIC=OFF
  ENABLE_MONGODB=OFF
  ENABLE_PDF=OFF
  ENABLE_DATA_MYSQL=OFF
  ENABLE_DATA_POSTGRESQL=OFF
  ENABLE_DATA_ODBC=OFF
  ENABLE_SEVENZIP=OFF
  ENABLE_APACHECONNECTOR=OFF
  ENABLE_CPPPARSER=OFF
  ENABLE_POCODOC=OFF
  ENABLE_CRYPTO=ON
  ENABLE_NETSSL=ON
  ENABLE_DATA=ON
  ENABLE_PAGECOMPILER=ON
  ENABLE_CPPUNIT=ON # Needs support in Poco
  ENABLE_TESTS=ON
)
