#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Web UI
#

.PHONY: clean all

clean all:
	$(MAKE) -C Common $(MAKECMDGOALS)
	$(MAKE) -C jQuery $(MAKECMDGOALS)
	$(MAKE) -C AngularJS $(MAKECMDGOALS)
	$(MAKE) -C AngularFileUpload $(MAKECMDGOALS)
	$(MAKE) -C Launcher $(MAKECMDGOALS)
	$(MAKE) -C SystemInformation $(MAKECMDGOALS)
	$(MAKE) -C Devices $(MAKECMDGOALS)
	$(MAKE) -C BundleAdmin $(MAKECMDGOALS)
	$(MAKE) -C Ace $(MAKECMDGOALS)
	$(MAKE) -C Playground $(MAKECMDGOALS)
	$(MAKE) -C OpenLayers $(MAKECMDGOALS)
	$(MAKE) -C GNSSTracking $(MAKECMDGOALS)
	$(MAKE) -C MQTT $(MAKECMDGOALS)
	$(MAKE) -C Console $(MAKECMDGOALS)
