#
# Makefile
#
# $Id$
#
# Makefile for macchina.io Web UI
#

.PHONY: clean all

clean all:
	$(MAKE) -C Launcher $(MAKECMDGOALS)
	$(MAKE) -C SystemInformation $(MAKECMDGOALS)
	$(MAKE) -C Devices $(MAKECMDGOALS)
	$(MAKE) -C BundleAdmin $(MAKECMDGOALS)
