#
# Makefile
#
# $Id: //poco/1.4/JS/OPC/Makefile#1 $
#
# Makefile for Poco JS OPC library
#

include $(POCO_BASE)/build/rules/global

objects = ClientWrapper

target         = PocoJSOPC
target_version = 1
target_libs    = PocoJSCore PocoOPC PocoFoundation v8

include $(POCO_BASE)/build/rules/lib
