#
# Makefile
#
# Makefile for Poco JS Data library
#

include $(POCO_BASE)/build/rules/global

objects = SessionWrapper RecordSetWrapper

target         = PocoJSData
target_version = 1
target_libs    = PocoJSCore PocoData PocoFoundation v8

include $(POCO_BASE)/build/rules/lib
