#
# Makefile
#
# Makefile for Poco OSP Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C BundleContainer $(MAKECMDGOALS)
	$(MAKE) -C BundleServer $(MAKECMDGOALS)
	$(MAKE) -C ServiceListener $(MAKECMDGOALS)
	$(MAKE) -C GreetingService $(MAKECMDGOALS)
	$(MAKE) -C Greeter $(MAKECMDGOALS)
	$(MAKE) -C Extensible $(MAKECMDGOALS)
	$(MAKE) -C Extension $(MAKECMDGOALS)
	$(MAKE) -C Preferences $(MAKECMDGOALS)
	$(MAKE) -C SimpleAuthService $(MAKECMDGOALS)
	$(MAKE) -C WebPage $(MAKECMDGOALS)
	$(MAKE) -C WebIndex $(MAKECMDGOALS)
	$(MAKE) -C WebInfo $(MAKECMDGOALS)
	$(MAKE) -C WebSession $(MAKECMDGOALS)
	$(MAKE) -C WebEvent $(MAKECMDGOALS)
	$(MAKE) -C WebFilter $(MAKECMDGOALS)
	$(MAKE) -C WebEcho $(MAKECMDGOALS)
	$(MAKE) -C EchoCommand $(MAKECMDGOALS)
	$(MAKE) -C LogLevelCommand $(MAKECMDGOALS)
