#
# Makefile
#
# Makefile for jsrun
#

include $(POCO_BASE)/build/rules/global

objects = jsrun

target         = jsrun
target_version = 1
target_libs    = v8 PocoJSNet PocoJSData PocoJSCore PocoNetSSL PocoCrypto PocoNet PocoDataSQLite PocoData PocoRemotingNG PocoUtil PocoXML PocoJSON PocoFoundation

include $(POCO_BASE)/build/rules/exec
