#
# Makefile
#
# Makefile for jsrun
#

include $(POCO_BASE)/build/rules/global

objects = jsrun

target         = jsrun
target_version = 1
target_libs    = PocoJSNet PocoJSData PocoJSCore PocoNetSSL PocoCrypto PocoNet PocoDataSQLite PocoData PocoRemotingNG PocoUtil PocoXML PocoJSON PocoFoundation
target_extlibs = v8 v8_libplatform v8_libbase

include $(POCO_BASE)/build/rules/exec
