#
# Makefile
#
# Makefile for jsrun
#

include $(POCO_BASE)/build/rules/global

objects = jsrun

target         = jsrun
target_version = 1
target_libs    = PocoJSNet PocoJSData PocoJSCore PocoNetSSL PocoCrypto PocoNet PocoDataSQLite PocoData PocoUtil PocoXML PocoJSON PocoFoundation
target_extlibs = v8

include $(POCO_BASE)/build/rules/exec
